@Django_backend_host = http://localhost:8000

@Django_backend_auth = http://localhost:8000/api/auth

GET {{Django_backend_auth}}/profile
Accept: application/json

###
POST {{Django_backend_auth}}/register/
Content-Type: application/json

{
  "username": "johndoe",
  "email": "john@example.com",
  "password": "MySecurePass123",
  "password2": "MySecurePass123",
  "bio": "Full-stack developer based in Berlin"
}

###
POST {{Django_backend_auth}}/login/
Content-Type: application/json

{
  "username": "johndoe",
  "password": "MySecurePass123"

}
###

###
#  fetch sessions
GET {{Django_backend_host}}/api/chat/session
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNDM5ODI1LCJpYXQiOjE3NjI0Mzk1MjUsImp0aSI6IjQ0YWRjOWJhMjM5ODQ3MTRhMWVhMjFhYWE0MmQ3MjQ5IiwidXNlcl9pZCI6IjEifQ.ZBA1ruTpbhxlNSfqlOdL1SPfA5DYOT0eFUeU9MHHvn0
