# Generated by Django 5.2.7 on 2025-11-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
