# Generated by Django 5.2.7 on 2025-11-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatsession_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='stream_name',
            field=models.TextField(default='New Chat'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='stream_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
